import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from './providers';
import Link from 'next/link'
import React from 'react'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next JS Web3 App",
  description: "Generated by mrSunder",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <nav className="max-w mx-auto flex justify-center bg-gray-800 text-white p-4">
              <ul className="flex space-x-6">
                  <li>
                      <Link href="/" className="hover:underline">Home</Link>
                  </li>
                  <li>
                      <Link href="/game" className="hover:underline">Game</Link>
                  </li>
                  <li>
                      <Link href="/tracker" className="hover:underline">Tracker</Link>
                  </li>
              </ul>
          </nav>
          <div className="min-h-screen">
              <Providers>{children}</Providers>
          </div>
      </body>
    </html>
  );
}
